server:
  id: 'main'
  links:
    appeal: 'https://warz.one/discord'
    store: 'https://warz.one/store'
    discord: 'https://warz.one/discord'
    rules: 'https://warz.one/rules'

api:
  secret: 'authtoken'
  socket:
    url: 'ws://api:7000'
  http:
    url: 'http://api:8000'

chat:
  enabled: true
