version: "3"

services:
  rs-redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - rs-mars-api:/data
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    expose:
      - "6379"
    networks:
      - rs-api
  kotlin-redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - kotlin-mars-api:/data
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    expose:
      - "6379"
    networks:
      - kotlin-api
  rs-mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - rs-mars-api:/data/db
    ports:
      - "27017"
    networks:
      - rs-api
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  kotlin-mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - kotlin-mars-api:/data/db
    ports:
      - "27017"
    networks:
      - kotlin-api
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  rs-api-srv:
    image: ghcr.io/chatasma/mars-api-rs:master
    hostname: rsapi01
    restart: unless-stopped
    depends_on:
      - "rs-redis"
      - "rs-mongo"
    networks:
      - rs-api
    ports:
      - "7000"
      - "8000:8000"
    environment:
      - MARS_API_TOKEN
      - MARS_CONFIG_PATH=./config/config.properties
      - MARS_BROADCASTS_PATH=./config/broadcasts.yml
      - MARS_LEVEL_COLORS_PATH=./config/level_colors.yml
      - MARS_PUNTYPES_PATH=./config/puntypes.yml
      - MARS_JOIN_SOUNDS_PATH=./config/join_sounds.yml
    volumes:
      - ./config/rs-api:/app/bin/config
    working_dir: /app/bin
  kotlin-api-srv:
    image: ghcr.io/warzone/mars-api:master
    hostname: kotlinapi01
    restart: unless-stopped
    depends_on:
      - "kotlin-redis"
      - "kotlin-mongo"
    networks:
      - kotlin-api
    ports:
      - "3000:3000"
    environment:
      - MARS_API_TOKEN
      - MARS_CONFIG_PATH=./config/config.properties
      - MARS_BROADCASTS_PATH=./config/broadcasts.yml
      - MARS_LEVEL_COLORS_PATH=./config/level_colors.yml
      - MARS_PUNTYPES_PATH=./config/puntypes.yml
      - MARS_JOIN_SOUNDS_PATH=./config/join_sounds.yml
    volumes:
      - ./config/kotlin-api:/usr/mars-api/config

volumes:
  rs-mars-api:
  kotlin-mars-api:

networks:
  rs-api:
  kotlin-api:
